# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc19edee46036b633f585828d6e96a40b213084cc0c2cef66c8c9385aadb3a56475089467368c65517edc1ae4689b4cd06859ad658af6d600170eedccb2f6f7a

test:
  secret_key_base: 49eee6c2dd91710ba7a824211b64dae715014abdc2fc3cc87d3e444fd3e5cbf1e61357723da57fc12023e6ab4264ad0433a7b0cab15bb91b94cb6cc1a3fbbc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
